=== Corvax-Fisher/Mosaics-Game/Mosaics-Game/xml/SVG_index.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="SVGFiles" type="SVGFilesType"/>
	
	<xsd:complexType name="SVGFilesType">
		<xsd:sequence>
			<xsd:element name="SVG" type="SVGType" maxOccurs="unbounded" minOccurs="0"/>
		</xsd:sequence>	
	</xsd:complexType>
				
	<xsd:complexType name="SVGType">
		<xsd:sequence>
			<xsd:element name="Name" type="xsd:string"/>
			<xsd:element name="Category" type="xsd:string"/>
			<xsd:element name="Width" type="xsd:positiveInteger"/>
			<xsd:element name="Length" type="xsd:positiveInteger"/>
			<xsd:element name="Dif" type="xsd:string"/>
		</xsd:sequence>	
			<xsd:attribute name="Filename" type="xsd:string" use="required" />
	</xsd:complexType>
				
		
</xsd:schema>

=== Corvax-Fisher/Mosaics-Game/Mosaics-Game/xml/svg_index.xml
<?xml version="1.0"?>
<SVGFiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml/SVG_index.xsd">
  <SVG Filename="mouth.svg">
    <Name>mouth</Name>
    <Category>Individual Patterns</Category>
    <Width>8</Width>
    <Length>8</Length>
    <Dif>Normal</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="America.svg">
    <Name>America</Name>
    <Category>Countries and Flags</Category>
    <Width>18</Width>
    <Length>12</Length>
    <Dif>Normal</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="Bahrain.svg">
    <Name>Bahrain</Name>
    <Category>Countries and Flags</Category>
    <Width>18</Width>
    <Length>12</Length>
    <Dif>Normal</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="Germany.svg">
    <Name>Germany</Name>
    <Category>Countries and Flags</Category>
    <Width>18</Width>
    <Length>12</Length>
    <Dif>Easy</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="Daenemark.svg">
    <Name>Daenemark</Name>
    <Category>Countries and Flags</Category>
    <Width>18</Width>
    <Length>12</Length>
    <Dif>Easy</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="Smiley1.svg">
    <Name>Smiley1</Name>
    <Category>Humans and Animals</Category>
    <Width>24</Width>
    <Length>24</Length>
    <Dif>Normal</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="Doggy.svg">
    <Name>Doggy</Name>
    <Category>Individual Patterns</Category>
    <Width>12</Width>
    <Length>12</Length>
    <Dif>Easy</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="Otaku.svg">
    <Name>Otaku</Name>
    <Category>Individual Patterns</Category>
    <Width>18</Width>
    <Length>12</Length>
    <Dif>Normal</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="Schwarze_Rauten.svg">
    <Name>Schwarze_Rauten</Name>
    <Category>Symmetrical Patterns</Category>
    <Width>24</Width>
    <Length>24</Length>
    <Dif>Normal</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="Green_Mini_Pencils.svg">
    <Name>Green_Mini_Pencils</Name>
    <Category>Things</Category>
    <Width>8</Width>
    <Length>8</Length>
    <Dif>Easy</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="Krueppel_Hand.svg">
    <Name>Krueppel_Hand</Name>
    <Category>Humans and Animals</Category>
    <Width>12</Width>
    <Length>18</Length>
    <Dif>Normal</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="Rote_Ampel.svg">
    <Name>Rote_Ampel</Name>
    <Category>Things</Category>
    <Width>24</Width>
    <Length>24</Length>
    <Dif>Normal</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="Smiley_Ampel.svg">
    <Name>Smiley_Ampel</Name>
    <Category>Things</Category>
    <Width>12</Width>
    <Length>18</Length>
    <Dif>Normal</Dif>
    <Permitted>true</Permitted>
  </SVG>
  <SVG Filename="TEST.svg">
    <Name>TEST</Name>
    <Category>Countries and Flags</Category>
    <Width>8</Width>
    <Length>8</Length>
    <Dif>Hard</Dif>
    <Permitted>false</Permitted>
  </SVG>
  <SVG Filename="Test2.svg">
    <Name>Test2</Name>
    <Category>Countries and Flags</Category>
    <Width>8</Width>
    <Length>8</Length>
    <Dif>Easy</Dif>
    <Permitted>true</Permitted>
  </SVG>
</SVGFiles>
